@EndPoint.Minimal.Api_HostAddress = http://localhost:5239

### دریافت لیست ژانرها
GET {{EndPoint.Minimal.Api_HostAddress}}/genres
Accept: application/json

### ایجاد ژانر جدید
POST {{EndPoint.Minimal.Api_HostAddress}}/createGenre
Content-Type: application/json
Accept: application/json

{
  "name": "Science",
  "description": "Science fiction focusing on intense"
}


### دریافت یک ژانر بر اساس id
GET http://localhost:5239/genre/12F06DE8-C4BB-42E2-79A2-08DD1D3060C4